### ISSUE TITLE
blob.polygone.art isn't responding

### ISSUE THREAD

**Issue by TimAidley** [arodic/polygon-download#4]
Hi, blob.polygone.art has stopped responding, so I am unable to download any of the sketches :(

**Comment by arodic** [comment]
Hey,

thanks for the heads up!

Sorry about that. My UPS failed and server was down for a few hours. Please
try again.

**Comment by TimAidley** [comment]
Wow - thanks for replying so quickly! And I really appreciate you having
saved all this amazing art.

**Comment by arodic** [comment]
You're welcome!
